---
title: "G-CoMS 병상운용현황"
author: "경기도 코로나19 긴급대책단"
output:
  word_document:
    reference_docx: style-ref.docx
  pdf_document: default
classoption: landscape
geometry: left=1cm,right=1cm,top=0cm,bottom=0cm
header-includes: \usepackage{kotex} \usepackage[doublespacing]{setspace} \usepackage{multirow} 
params:
  data: 1
  data2: 1
  dtime: 1
date: "`r params$dtime`"
editor_options: 
  chunk_output_type: console
---
  


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, dev = "png", fig.showtext=TRUE)
library(dplyr)
library(ggplot2)
library(tidyr)
library(gridExtra)

## Apply font from local ttf file
library(showtext)
showtext.opts(dpi = 330)                                ## same to rmd chunk
font_add("GyeonggiBatangR", "/home/js/ShinyApps/corona-sickbed/www/Batang_Regular.ttf")
font_add("GyeonggiBatangB", "/home/js/ShinyApps/corona-sickbed/www/Batang_Bold.ttf")

data_raw <- params$data %>%
  group_by(분류1) %>%
  summarise(사용병상 = sum(사용병상), 가용병상 = sum(가용병상)) 

data_raw2 <- params$data
```

```{r echo=FALSE, dpi=330, fig.height=2.5, fig.width=10}
## data
data <- data_raw %>%
  filter(분류1 == "합계") %>%
  gather(key = "상태", value = "병상수", 사용병상:가용병상) %>%
  mutate(lab.ypos = cumsum(병상수) - 0.5*병상수)

## pie1
pie1 <- ggplot(data, aes(x = 2, y = 병상수, fill = 상태)) +
  geom_bar(stat = "identity", color = "white") +
  coord_polar(theta = "y", start = 0) +
  geom_text(
    aes(y = lab.ypos, 
        label = paste0(data$상태, "\n", data$병상수, "/", sum(data$병상수))
    ),
    family = "GyeonggiBatangB",
    size = 1.5
  ) +
  scale_fill_manual(values = c("#4d80e4", "#e5dfdf")) +
  theme_void() +
  xlim(.5, 2.5) +
  labs(
    title = "전체 병상 가동률"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size = 8, family = "GyeonggiBatangB"),
    text = element_text(family = "GyeonggiBatangB")
  ) +
  annotate(
    geom = 'text', 
    x = 0.5, y = 0, 
    label = paste0(round(data$병상수[1]/sum(data$병상수)*100, 1), "%"),
    family = "GyeonggiBatangB",
    size = 3.5
  )

# data2
data <- data_raw %>%
  filter(분류1 == "중환자실") %>%
  gather(key = "상태", value = "병상수", 사용병상:가용병상) %>%
  mutate(lab.ypos = cumsum(병상수) - 0.5*병상수)

# pie2
pie2 <- ggplot(data, aes(x = 2, y = 병상수, fill = 상태)) +
  geom_bar(stat = "identity", color = "white") +
  coord_polar(theta = "y", start = 0) +
  geom_text(
    aes(y = lab.ypos, 
        label = paste0(data$상태, "\n", data$병상수, "/", sum(data$병상수))
    ),
    family = "GyeonggiBatangB",
    size = 1.5
  ) +
  scale_fill_manual(values = c("#db4455", "#e5dfdf")) +
  theme_void() +
  xlim(.5, 2.5) +
  labs(
    title = "중환자실 가동률"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size = 8, family = "GyeonggiBatangB"),
    text = element_text(family = "GyeonggiBatangB")
  ) +
  annotate(
    geom = 'text', 
    x = 0.5, y = 0, 
    label = paste0(round(data$병상수[1]/sum(data$병상수)*100, 1), "%"),
    family = "GyeonggiBatangB",
    size = 3.5
  )

# pie3
data1 <- params$data2 %>%
  mutate(가용객실수 = 총객실 - 사용객실) %>%
  select(c("센터명", "사용객실", "가용객실수"))
colnames(data1) <- c("병원명", "사용객실", "가용객실")
data1 <- data1 %>%
  gather(key = "상태", value = "병상수", 사용객실:가용객실) %>%
  # filter(가용병상 != 0 & 사용병상 != 0)
  group_by(상태) %>%
  summarise(병상수 = sum(병상수)) %>%
  mutate(상태 = factor(상태, levels = c("가용객실", "사용객실"), order = TRUE)) %>%
  arrange(desc(상태)) %>%
  mutate(lab.ypos = cumsum(병상수) - 0.5*병상수) 

pie3 <- ggplot(data1, aes(x = 2, y = 병상수, fill = 상태)) +
  geom_bar(stat = "identity", color = "white") +
  coord_polar(theta = "y", start = 0) +
  geom_text(
    aes(y = lab.ypos, 
        label = paste0(data1$상태, "\n", data1$병상수, "/", sum(data1$병상수))
    ),
    family = "GyeonggiBatangB",
    size = 1.5
  ) +
  scale_fill_manual(values = c("#02a8a8", "#e5dfdf")) +
  theme_void() +
  xlim(.5, 2.5) +
  labs(
    title = "생활치료센터 가동률"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size = 8, family = "GyeonggiBatangB"),
    text = element_text(family = "GyeonggiBatangB")
  ) +
  annotate(
    geom = 'text', 
    x = 0.5, y = 0, 
    label = paste0(round(data1$병상수[1]/sum(data1$병상수)*100, 1), "%"),
    family = "GyeonggiBatangB",
    size = 3.5
  )

grid.arrange(pie1, pie2, pie3, nrow = 1)
```

```{r echo=FALSE, dpi=330, fig.height=3, fig.width=10, warning=FALSE}
## Bar Graph1 ----
data <- data_raw2 %>%
  filter(분류1 == "합계") %>%
  mutate(병원명 = factor(병원명, level = .$병원명)) %>%
  gather("가용", "병상수", 사용병상:가용병상) %>%
  mutate(가용 = factor(가용, level = c("사용병상", "가용병상"), ordered = TRUE))

bar1 <- data %>%
  ggplot(aes(병원명, 병상수, fill = 가용)) +
  geom_col(width = 0.7) +
  geom_text(
    aes(label = ifelse(병상수 != 0, 병상수, NA)), 
    position = position_stack(vjust = 0.5),
    family = "GyeonggiBatangB",
    size = 2
  ) +
  scale_fill_manual(values = c("#e5dfdf", "#4d80e4")) +
  labs(
    title = "병원별 병상운용 현황",
    x = "",
    y = ""
  ) +
  theme_void(base_family = "GyeonggiBatangB") +
  theme(
    legend.position = "none",
    legend.text = element_text(family = "GyeonggiBatangB", size = 5),
    legend.title = element_text(family = "GyeonggiBatangB", size = 5),
    plot.title = element_text(hjust = 0.5, size = 8, family = "GyeonggiBatangB"),
    text = element_text(family = "GyeonggiBatangB"),
    axis.text.x = element_text(angle = 45, hjust = 0.7, vjust = 1, family = "GyeonggiBatangB", size = 5),
  )

data <- data_raw2 %>%
  filter(분류1 == "중환자실") %>%
  filter(총병상 != 0) %>%
  mutate(병원명 = factor(병원명, level = .$병원명)) %>%
  gather("가용", "병상수", 사용병상:가용병상) %>%
  mutate(가용 = factor(가용, level = c("사용병상", "가용병상"), ordered = TRUE))

bar2 <- data %>%
  ggplot(aes(병원명, 병상수, fill = 가용)) +
  geom_col() +
  geom_text(
    aes(label = ifelse(병상수 != 0, 병상수, NA)), 
    position = position_stack(vjust = 0.5),
    family = "GyeonggiBatangB",
    size = 2
  ) +
  scale_fill_manual(values = c("#e5dfdf", "#db4455")) +
  labs(
    title = "중환자실 운용 현황",
    x = "",
    y = ""
  ) +
  theme_void(base_family = "GyeonggiBatangB") +
  theme(
    legend.position = "none",
    legend.text = element_text(family = "GyeonggiBatangB", size = 5),
    legend.title = element_text(family = "GyeonggiBatangB", size = 5),
    plot.title = element_text(hjust = 0.5, size = 8, family = "GyeonggiBatangB"),
    text = element_text(family = "GyeonggiBatangB"),
    axis.text.x = element_text(angle = 45, hjust = 0.8, vjust = 1, family = "GyeonggiBatangB", size = 5)
  )

bar3 <- params$data2 %>%
      mutate(가용객실 = 총객실 - 사용객실) %>%
      select(센터명, 가용객실, 사용객실) %>%
      mutate(센터명 = factor(센터명, level = .$센터명))%>%
      gather("가용", "병상수", 가용객실:사용객실) %>%
      mutate(가용 = factor(가용, levels = c("사용객실", "가용객실"))) %>%
  ggplot(aes(센터명, 병상수, fill = 가용)) +
  geom_col(width = 0.3) +
  geom_text(
    aes(label = ifelse(병상수 != 0, 병상수, NA)), 
    position = position_stack(vjust = 0.5),
    family = "GyeonggiBatangB",
    size = 2
  ) +
  scale_fill_manual(values = c("#e5dfdf", "#02a8a8")) +
  labs(
    title = "생활치료센터 운용 현황",
    x = "",
    y = ""
  ) +
  theme_void(base_family = "GyeonggiBatangB") +
  theme(
    legend.position = "none",
    legend.text = element_text(family = "GyeonggiBatangB", size = 5),
    legend.title = element_text(family = "GyeonggiBatangB", size = 5),
    plot.title = element_text(hjust = 0.5, size = 8, family = "GyeonggiBatangB"),
    text = element_text(family = "GyeonggiBatangB"),
    axis.text.x = element_text(angle = 45, hjust = 0.8, vjust = 1, family = "GyeonggiBatangB", size = 5)
  )
      
  


grid.arrange(bar1, bar2, bar3, widths = c(0.6, 0.25, 0.15), nrow = 1)
```




